spring:
  application:
    name: activitiapproval
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle-test.lecarlink.com:1521:otest
    username: ${YM_USERNAME}
    password: ${YM_PASSWD}
    druid:
      validationQuery: SELECT 1 FROM DUAL
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  activiti:
    check-process-definitions: false
#    mail-server-host: smtp.exmail.qq.com
#    mail-server-user-name: noreply-test@lecarlink.com
#    mail-server-password: Lecar0000002017
#    mail-server-port: 25
  mvc:
    static-path-pattern: /**

# spring boot 邮件配置    
  mail:
    host: smtp.exmail.qq.com
    port: 25
    username: noreply-test@lecarlink.com
    password: Lecar0000002017
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000

#线上环境oracle必须配置　
  jpa:
    hibernate:
      ddl-auto: false
    show-sql: false
    properties:
      hibernate:
        default_schema: orcl
        dialect: org.hibernate.dialect.OracleDialect
server:
  port: 50001
  context-path: /lcActivitiService
logging:
  level:
    com:
      looedu:
        mapper: debug
    
 # 配置mybatis-plus
#mybatis-plus:
#  # 配置扫描xml
#  mapper-locations: classpath*:lc/activiti/contract/mapper/base/*.xml
#  # 实体扫描，多个package用逗号或者分号分隔
#  type-aliases-package: lc.activiti.contract.entity,lc.activiti.contract.dao.base
#  global-config:
#    # 逻辑删除配置
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector   
mybatis:
#    type-aliases-package: lc.activiti.contract.entity,lc.activiti.contract.dao.base,lc.activiti.common.entity,lc.activiti.common.dao,lc.activiti.common.dao.base,lc.activiti.expense.dao.base
#    type-handlers-package: lc.activiti.contract
#    mapper-locations: classpath*:lc/activiti/contract/mapper/base/*.xml,**/mapper/*.xml,lc/activiti/common/mapper/base/*.xml,lc/activiti/common/mapper/*.xml,lc/activiti/expense/mapper/base/*.xml
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
#关闭安全验证
security:
  ignored: /**
  basic:
    enabled: false
management:
  security:
    enabled: false
# 邮件相关
# 发件邮件
lc:
 mail:
  fromMail:
   addr: noreply-test@lecarlink.com
 business-sys-url: http://192.168.1.187:9090
 #token在请求头中的位置（token的组成<key+param+uri>）
 headerString: Authorization
 #DES加密算法的key
 secretKey: 1q2w3e4r
 #token的起始的key的原码
 originalWord: q1w2e3r4
 #新oa服务
 newOaService: https://noa-tst.lecarlink.com/lecar-oadata-service